# DS 3000/CS 3200 Lab 1

Due: Tuesday May 13 in-class

### Submission Instructions
Upload this `ipynb` file to GitHub, and then to Gradescope.  To ensure that your submitted `ipynb` file represents your latest code, make sure to give a fresh `Kernel > Restart & Run All` just before uploading the `ipynb` file to GitHub and verify that the correct version is represented on Gradescope.

### Tips for success
- Collaborate: bounce ideas off of each other, if you are having trouble you can ask your classmates or Dr. Gerber for help with specific issues, however...
- [(See)](http://www.northeastern.edu/osccr/academic-integrity), i.e. you are welcome to **talk about/discuss** (*not* show or allow each other to copy your answers to) the problems.

# Part 1 (40 points): Intro to Markdown

Use the markdown language below to create your own brief wikipedia-esque description of a topic related to International Government and Politics. 

Your mini-wiki page must include:
- three headers: a title, subtitle and subsubtitle (the #, ##, ### syntax)
- an embedded image from a web address (use an [image hosting site](https://makeawebsitehub.com/free-photo-hosting/) if you'd like to upload your own)
- a **markdown** table of size at least 9 cells (i.e. 3 by 3, or 5 by 2)
- a list in **markdown**
- a link to another website

To practice typing in math mode, also include a LaTeX formula describing how your final grade is going to be calculated based on the syllabus, something like:

$$grade = weight_1*score_1 + weight_2*score_2$$

Please be **brief** in your text.  Aim for roughly 3 sentences total of text.

# 2025 India–Pakistan conflict

## Operation Sindoor 

### Missile Strikes
On 7 May 2025, the Indian Armed Forces launched a series of 14 attacks, codenamed Operation Sindoor, targeting nine locations in Pakistani-administered Kashmir and Pakistan's Punjab province.

![Terrorist camp in Mehmoona Joya](https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Operation_Sindoor_Targets_Terrorist_Camp_Mehmoona_Joya.png/960px-Operation_Sindoor_Targets_Terrorist_Camp_Mehmoona_Joya.png)

| Strike |  Places  | Province/City |
|---|---------------|--------------|
| 2 | Syedna Bilal  | Muzaffarabad |
| 3 | Gulpur        | Kotli        |
| 4 | Barnala       | Bhimber      |
| 5 | Abbas Kotli   | Kolti        |
| 6 | Bahawalpur    | Punjab       |
| 7 | Murdike       | Punjab       |
| 8 | Sarjal        | Punjab       |
| 9 | Mehmoona Joya | Punjab       |

### Countries Involved In the Talks
1. India
2. Pakistan
3. USA

Reference [Wikipedia](https://en.wikipedia.org/wiki/2025_India–Pakistan_conflict)





## Grade Breakdown
$$grade = Homeworks  And  Labs * .6 + In Class Activities * .4$$

# Part 2: Numpy
## Part 2.1: Creating Arrays (10 points)

Create the following two arrays using the NumPy library and then print them out. Call the first array `array_a` and the second array `array_b` (make sure you keep the `import` statement below):

$$\mathbf{array_a} = \begin{bmatrix}3 & 8 & -2 & 3\\
.5 & -1 & 6 & 4\\
-5 & 7 & -42 & 2
\end{bmatrix}$$

$$\mathbf{array_b} = \begin{bmatrix}42 & 38 & 34\\
30 & 26 & 22\\
18 & 14 & 10\\
6 & 2 & -2\\
-6 & -10 & -14
\end{bmatrix}$$

In [140]:
# make sure to import numpy library
import numpy as np

In [141]:
array_a = np.array([[3, 8, -2, 3], [.5, -1, 6, 4], [-5, 7, -42, 2]])
array_b = np.array([[42, 38, 34], [30, 26, 22], [18, 14, 10], [6, 2, -2], [-6, -10, -14]])


In [142]:
# uncomment below to print array_a
array_a

array([[  3. ,   8. ,  -2. ,   3. ],
       [  0.5,  -1. ,   6. ,   4. ],
       [ -5. ,   7. , -42. ,   2. ]])

In [143]:
# uncomment below to print array_b
array_b

array([[ 42,  38,  34],
       [ 30,  26,  22],
       [ 18,  14,  10],
       [  6,   2,  -2],
       [ -6, -10, -14]])

## Part 2.2: Exploring Arrays (15 points)

1. Give the shape, size, ndim, and nbytes for each of the two arrays.
1. Take the transpose of both arrays. Call these `t_array_a` and `t_array_b`.
1. Try to add `array_a` and `t_array_b` (*prove* and *show* you did this with commented out code), then remove the last column of `t_array_b` and try to add them again. In a markdown cell, explain what happened.

In [144]:
array_a.shape

(3, 4)

In [145]:
array_b.shape

(5, 3)

In [146]:
array_a.size

12

In [147]:
array_b.size

15

In [148]:
array_a.ndim

2

In [149]:
array_b.ndim

2

In [150]:
array_a.nbytes

96

In [151]:
array_b.nbytes

120

In [152]:
t_array_a = array_a.T
t_array_a

array([[  3. ,   0.5,  -5. ],
       [  8. ,  -1. ,   7. ],
       [ -2. ,   6. , -42. ],
       [  3. ,   4. ,   2. ]])

In [153]:
t_array_b = array_b.T
t_array_b

array([[ 42,  30,  18,   6,  -6],
       [ 38,  26,  14,   2, -10],
       [ 34,  22,  10,  -2, -14]])

In [154]:
# np.add(array_a, t_array_b)

t_array_b = np.delete(t_array_b, -1, axis=1)
t_array_b

np.add(array_a, t_array_b)

array([[ 45. ,  38. ,  16. ,   9. ],
       [ 38.5,  25. ,  20. ,   6. ],
       [ 29. ,  29. , -32. ,   0. ]])

The shapes of the two before don't fit (3,4 and 3,5), but once you delete the last column they do fit and you can add them. 

# Part 3: Pandas
## Part 3.1: Reading in Data (5 points)

On Canvas is the `train_stations_europe.csv` file. It was adapted from [this Kaggle data set](https://www.kaggle.com/datasets/headsortails/train-stations-in-europe). Read this data set in, using the `id` as the index column, and print the first few rows of the data. Make sure you keep the `import` statement below!

In [155]:
# make sure to import pandas library
import pandas as pd

In [156]:
df = pd.read_csv("~/Desktop/train_stations_europe.csv")

## Part 3.2: Manipulating Data (20 points)

1. Create a subset of the data set which (a) **includes** only train stations in Belgium and (b) **excludes** all train stations which are **not** in a city. Make sure to save this subset as a new data frame and print the first few rows of the data.
1. Use the `.describe()` function to produce summary statistics for the subset from the previous part. Create a markdown cell and explain:
    - What Series did the `.describe()` function run on? What Series did it not run on? What is the difference, and what does this mean the `.describe()` function is used for?

In [157]:
new_df = df.loc[(df["country"] == "BE") & (df["is_city"] == True)]

new_df.head()

id              name   latitude  longitude  parent_station_id country  \
4520  5964         Antwerpen  51.221722   4.405860                NaN      BE   
4522  5970    Blandain Ville  50.617431   3.263740                NaN      BE   
4525  5974         Bruxelles  50.846520   4.351739                NaN      BE   
4533  6003       Quevy Ville        NaN        NaN                NaN      BE   
4535  6006  Sterpenich Ville        NaN        NaN                NaN      BE   

            time_zone  is_city  is_main_station  is_airport  
4520  Europe/Brussels     True            False       False  
4522  Europe/Brussels     True            False       False  
4525  Europe/Brussels     True            False       False  
4533  Europe/Brussels     True            False       False  
4535  Europe/Brussels     True            False       False

In [158]:
df.describe()

id      latitude     longitude  parent_station_id
count  64037.000000  62142.000000  62142.000000        4014.000000
mean   34889.088183     48.319515      8.139495       18346.361983
std    19581.801377      5.205744      6.319726       14109.347122
min        1.000000     31.629472    -16.920004           1.000000
25%    17945.000000     46.185354      6.240894        7527.000000
50%    34848.000000     47.281206      8.405040       16756.000000
75%    52137.000000     50.613890     11.875845       28388.500000
max    68179.000000     68.441670     44.753210       67935.000000

.describe() only seems to work on series that contain numbers like id, latitude, etc. And does not work on series that do not contain numbers like name, is_main_station, etc. This means that the .describe function() will only work on numerical series and produces statistical data such as min, mean, std, etc for them, which makes sense because you can't do such calculations for strings or booleans. 

# Part 4: GitHub (10 points)

When you finish the first three parts, give one last restart and run all to this file. Then, go to the [DS 3000 GitHub](https://github.com/eaegerber/ds3000_summer25), fork it and then clone it to your local machine. Then:

- In the forked and cloned ds3000_summer25 repo, make a new branch (`git checkout -b lab-upload`)
- Create a folder with your name (as Dr. Gerber did)
- Navigate to that folder and place this jupyter notebook inside
- Add the file as the change to be committed (`git add .\Lab1_MyName.ipynb`)
- Check `git status`, your changes should be staged
- Commit the changes with a short message (`git commit -m "My message"`)
- Push the repository to GitHub (`git push origin lab-upload`)
- Navigate the the GitHub in the browser and create a pull request
- Once the pull request is merged, you can delete your branch in the "Pull Requests" tab in the browser
- Finally, upload the Lab to Gradescope. When you do so, it will give you the option to do it via GitHub; do that.